import { Box, Flex } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
import { CoverAnime } from "lib/Anime"
import { motion } from "framer-motion"
import BorderAniBox from "components/uiParts/BorderAniBox"
import React, { useEffect, useState, useReducer } from "react"
import { useChildrenAnimation } from "hooks/useChildrenAnimation"

const sequence: string[] = ["border", "cover"]

const Home: NextPage = () => {
	const { state, goNextAnime } = useChildrenAnimation(sequence)

	useEffect(() => {
		goNextAnime()
	}, [goNextAnime])

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Flex
				width="100%"
				height="100vh"
				justifyContent="center"
				alignItems="center"
			>
				<Box>
					<CoverAnime
						w={"95vw"}
						maxW={600}
						h={300}
						currentAnimeTarget={sequence[state.sequenceIndex]}
						animeTarget={"cover"}
						onNext={goNextAnime}
					>
						<Box position="absolute" />
					</CoverAnime>
					<BorderAniBox
						w={"95vw"}
						maxW={600}
						h={300}
						currentAnimeTarget={sequence[state.sequenceIndex]}
						animeTarget={"border"}
						onNext={goNextAnime}
					></BorderAniBox>
				</Box>
			</Flex>
		</div>
	)
}

export default Home
