import { Box, ButtonGroup, Flex, Heading } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
import { CoverAnime } from "lib/Anime"
import BorderAniBox from "components/uiParts/BorderAniBox"
import React, { useEffect, useState, useReducer } from "react"
import Button from "components/uiParts/Button"
import { useSequence } from "hooks/useSequence"
import { AiOutlineArrowRight } from "react-icons/ai"

const Home: NextPage = () => {
	const { next, phase } = useSequence(["border", "cover", "header", "", ""])

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Flex
				width="100%"
				height="100vh"
				justifyContent="center"
				alignItems="center"
			>
				<Box position="relative">
					<CoverAnime
						w={"95vw"}
						maxW={600}
						h={200}
						running={phase == "cover"}
						onEnd={next}
						coverColors={["black", "gray"]}
						coverOrigin={"top"}
					>
						<Flex
							w={"95vw"}
							maxW={600}
							h={200}
							position="absolute"
							bgColor={"gray.100"}
							p={8}
							justifyContent="center"
							flexDir="column"
							gridGap={3}
						>
							<CoverAnime
								w={400}
								maxW={"100%"}
								h={`60px`}
								coverColors={["black"]}
								running={phase === "header"}
								onEnd={next}
							>
								<Heading
									as="h1"
									size="2xl"
									fontFamily="Raleway"
									whiteSpace="nowrap"
								>
									Happa8 Website
								</Heading>
							</CoverAnime>
							<ButtonGroup>
								<CoverAnime
									width={"max-content"}
									h={"max-content"}
									coverColors={["black"]}
									running={phase === "header"}
									onEnd={next}
								>
									<Button rightIcon={<AiOutlineArrowRight />}>Who am I?</Button>
								</CoverAnime>
								<CoverAnime
									width={"max-content"}
									h={"max-content"}
									coverColors={["black"]}
									running={phase === "header"}
									onEnd={next}
								>
									<Button rightIcon={<AiOutlineArrowRight />}>WORKS</Button>
								</CoverAnime>
							</ButtonGroup>
						</Flex>
					</CoverAnime>
					<BorderAniBox
						w={"95vw"}
						maxW={600}
						h={200}
						running={phase === "border"}
						onEnd={next}
						zIndex={0}
						position={"absolute"}
						top={0}
					></BorderAniBox>
				</Box>
			</Flex>
		</div>
	)
}

export default Home
